// Code generated by templ@v0.2.364 DO NOT EDIT.

package user

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func getDetailsURL(user User) string {
	return "api/user/" + user.ID + "/details"
}

func getUserDetailsID(user User, target bool) string {
	if target {
		return "#userDetails" + user.ID
	}
	return "userDetails" + user.ID
}

func UserItem(user User) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<tr id=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(user.ID))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\"><td class=\"px-6 py-4 whitespace-no-wrap border-b border-gray-300\">")
		if err != nil {
			return err
		}
		var var_2 string = user.Name
		_, err = templBuffer.WriteString(templ.EscapeString(var_2))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</td><td class=\"px-6 py-4 whitespace-no-wrap border-b border-gray-300\">")
		if err != nil {
			return err
		}
		var var_3 string = user.Email
		_, err = templBuffer.WriteString(templ.EscapeString(var_3))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</td><td class=\"px-6 py-4 whitespace-no-wrap border-b border-gray-300\"><button class=\"text-blue-600 hover:text-blue-800 \"><i class=\"fas fa-edit\"></i></button><button class=\"text-red-600 hover:text-red-800\" hx-delete=\"api/user\" hx-target=\"closest tr\" hx-swap=\"outerHTML swap:500ms\" hx-confirm=\"Are you sure?\"><i class=\"fas fa-trash-alt\"></i></button><button class=\"text-green-600 hover:text-green-800\" hx-get=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(getDetailsURL(user)))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" hx-target=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(getUserDetailsID(user, true)))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" hx-swap=\"outerHTML\"><div id=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(getUserDetailsID(user, false)))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\"><i class=\"fa-solid fa-notes-medical\"></i></div></button></td></tr>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
