// Code generated by templ@v0.2.316 DO NOT EDIT.

package patients

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func PatientForm() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<div id=\"patientForm\" class=\"container mx-auto mt-8\"><form class=\"mt-4\" id=\"addPatientForm\" action=\"/patient/add\" method=\"POST\" hx-post=\"/patient/add\" hx-target=\"#patientList\" hx-select=\"#patientList\" hx-swap=\"outerHTML\"><h1 class=\"text-blue-500 text-5xl text-center\">")
		if err != nil {
			return err
		}
		var_2 := `Add New Patient`
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h1><div class=\"mb-4\"><label for=\"name\" class=\"block text-gray-700 text-sm font-bold mb-2\">")
		if err != nil {
			return err
		}
		var_3 := `Name`
		_, err = templBuffer.WriteString(var_3)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</label><input type=\"text\" id=\"name\" name=\"name\" class=\"form-input w-full rounded-md shadow-sm\" placeholder=\"Name\" required></div><div class=\"mb-4\"><label for=\"documentNumber\" class=\"block text-gray-700 text-sm font-bold mb-2\">")
		if err != nil {
			return err
		}
		var_4 := `Document Number`
		_, err = templBuffer.WriteString(var_4)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</label><input type=\"text\" id=\"documentNumber\" name=\"documentNumber\" class=\"form-input w-full rounded-md shadow-sm\" placeholder=\"123-456-789-90\" required></div><div class=\"mb-4\"><label for=\"email\" class=\"block text-gray-700 text-sm font-bold mb-2\">")
		if err != nil {
			return err
		}
		var_5 := `Email`
		_, err = templBuffer.WriteString(var_5)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</label><input type=\"email\" id=\"email\" name=\"email\" class=\"form-input w-full rounded-md shadow-sm\" placeholder=\"john@example.com\" required></div><div class=\"text-center\"><button type=\"submit\" class=\"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded\">")
		if err != nil {
			return err
		}
		var_6 := `Add Patient`
		_, err = templBuffer.WriteString(var_6)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</button></div></form></div>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = io.Copy(w, templBuffer)
		}
		return err
	})
}
